### ISSUE TITLE
superglue+superpoint实时性和资源消耗

### ISSUE THREAD

**Issue by TBetterman** [mingjitianming/superglue_apply#2]
很惊奇发现大兄弟也在做c++ version的superpoint和superglue！目前也在填坑中= =。想问问你现在这版的实时性和资源消耗情况如何，特征匹配效果好吗

**Comment by mingjitianming** [comment]
> 很惊奇发现大兄弟也在做c++ version的superpoint和superglue！目前也在填坑中= =。想问问你现在这版的实时性和资源消耗情况如何，特征匹配效果好吗

实时性与资源消耗与superpoint提取出的特征点数量是成正比的，特征点数量可以在superpoint.yaml中设置
测试用例可以再examples中找到，如果找到可以提速的方法欢迎指教

**Comment by TBetterman** [comment]
> > 很惊奇发现大兄弟也在做c++ version的superpoint和superglue！目前也在填坑中= =。想问问你现在这版的实时性和资源消耗情况如何，特征匹配效果好吗
> 
> 实时性与资源消耗与superpoint提取出的特征点数量是成正比的，特征点数量可以在superpoint.yaml中设置
> 测试用例可以再examples中找到，如果找到可以提速的方法欢迎指教

目前还在继续填坑中，看到你c++新特性用的很骚气啊

**Comment by mingjitianming** [comment]
> > > 很惊奇发现大兄弟也在做c++ version的superpoint和superglue！目前也在填坑中= =。想问问你现在这版的实时性和资源消耗情况如何，特征匹配效果好吗
> > 
> > 
> > 实时性与资源消耗与superpoint提取出的特征点数量是成正比的，特征点数量可以在superpoint.yaml中设置
> > 测试用例可以再examples中找到，如果找到可以提速的方法欢迎指教
> 
> 目前还在继续填坑中，看到你c++新特性用的很骚气啊

新特性确实能够减少代码量,期待你踩完坑后过来分享.
