### ISSUE TITLE
 error: ‘getProfilingMode’ is not a member of ‘torch::jit’

### ISSUE THREAD

**Issue by hellovuong** [mingjitianming/superglue_apply#3]
Hello,
Thank you for the C++ implementation. Unfortunately, I encountered errors with libtorch. 
`/home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp: In constructor ‘SuperGlue::SuperGlue(const YAML::Node&)’:
/home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:21:17: error: ‘getProfilingMode’ is not a member of ‘torch::jit’
     torch::jit::getProfilingMode() = false;
                 ^~~~~~~~~~~~~~~~
/home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:22:17: error: ‘getExecutorMode’ is not a member of ‘torch::jit’
     torch::jit::getExecutorMode() = false;
                 ^~~~~~~~~~~~~~~
/home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:22:17: note: suggested alternative: ‘getOperatorFor’
     torch::jit::getExecutorMode() = false;
                 ^~~~~~~~~~~~~~~
                 getOperatorFor
/home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:23:17: error: ‘setGraphExecutorOptimize’ is not a member of ‘torch::jit’
     torch::jit::setGraphExecutorOptimize(false);
                 ^~~~~~~~~~~~~~~~~~~~~~~~
/home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:23:17: note: suggested alternative: ‘GraphExecutorState’
     torch::jit::setGraphExecutorOptimize(false);
                 ^~~~~~~~~~~~~~~~~~~~~~~~
                 GraphExecutorState
`

I assumed that I may cause by the version of libtorch. I am using version 1.0.1. I am wondering which version libtorch that you are using?
Thanks,

**Comment by mingjitianming** [comment]
> Hello,
> Thank you for the C++ implementation. Unfortunately, I encountered errors with libtorch.
> `/home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp: In constructor ‘SuperGlue::SuperGlue(const YAML::Node&)’: /home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:21:17: error: ‘getProfilingMode’ is not a member of ‘torch::jit’ torch::jit::getProfilingMode() = false; ^~~~~~~~~~~~~~~~ /home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:22:17: error: ‘getExecutorMode’ is not a member of ‘torch::jit’ torch::jit::getExecutorMode() = false; ^~~~~~~~~~~~~~~ /home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:22:17: note: suggested alternative: ‘getOperatorFor’ torch::jit::getExecutorMode() = false; ^~~~~~~~~~~~~~~ getOperatorFor /home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:23:17: error: ‘setGraphExecutorOptimize’ is not a member of ‘torch::jit’ torch::jit::setGraphExecutorOptimize(false); ^~~~~~~~~~~~~~~~~~~~~~~~ /home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:23:17: note: suggested alternative: ‘GraphExecutorState’ torch::jit::setGraphExecutorOptimize(false); ^~~~~~~~~~~~~~~~~~~~~~~~ GraphExecutorState `
> 
> I assumed that I may cause by the version of libtorch. I am using version 1.0.1. I am wondering which version libtorch that you are using?
> Thanks,

the version is 1.6.0

**Comment by mingjitianming** [comment]
> > Hello,
> > Thank you for the C++ implementation. Unfortunately, I encountered errors with libtorch.
> > `/home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp: In constructor ‘SuperGlue::SuperGlue(const YAML::Node&)’: /home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:21:17: error: ‘getProfilingMode’ is not a member of ‘torch::jit’ torch::jit::getProfilingMode() = false; ^~~~~~~~~~~~~~~~ /home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:22:17: error: ‘getExecutorMode’ is not a member of ‘torch::jit’ torch::jit::getExecutorMode() = false; ^~~~~~~~~~~~~~~ /home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:22:17: note: suggested alternative: ‘getOperatorFor’ torch::jit::getExecutorMode() = false; ^~~~~~~~~~~~~~~ getOperatorFor /home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:23:17: error: ‘setGraphExecutorOptimize’ is not a member of ‘torch::jit’ torch::jit::setGraphExecutorOptimize(false); ^~~~~~~~~~~~~~~~~~~~~~~~ /home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:23:17: note: suggested alternative: ‘GraphExecutorState’ torch::jit::setGraphExecutorOptimize(false); ^~~~~~~~~~~~~~~~~~~~~~~~ GraphExecutorState `
> > I assumed that I may cause by the version of libtorch. I am using version 1.0.1. I am wondering which version libtorch that you are using?
> > Thanks,
> 
> the version is 1.6.0

```c++   
    torch::jit::getProfilingMode() = false;
    torch::jit::getExecutorMode() = false;
    torch::jit::setGraphExecutorOptimize(false);
```
是用来取消初次使用的一些优化来缩短初次的运行的时间，你也可以将他们注释掉

**Comment by hellovuong** [comment]
> > > Hello,
> > > Thank you for the C++ implementation. Unfortunately, I encountered errors with libtorch.
> > > `/home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp: In constructor ‘SuperGlue::SuperGlue(const YAML::Node&)’: /home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:21:17: error: ‘getProfilingMode’ is not a member of ‘torch::jit’ torch::jit::getProfilingMode() = false; ^~~~~~~~~~~~~~~~ /home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:22:17: error: ‘getExecutorMode’ is not a member of ‘torch::jit’ torch::jit::getExecutorMode() = false; ^~~~~~~~~~~~~~~ /home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:22:17: note: suggested alternative: ‘getOperatorFor’ torch::jit::getExecutorMode() = false; ^~~~~~~~~~~~~~~ getOperatorFor /home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:23:17: error: ‘setGraphExecutorOptimize’ is not a member of ‘torch::jit’ torch::jit::setGraphExecutorOptimize(false); ^~~~~~~~~~~~~~~~~~~~~~~~ /home/vuong/Code/superglue_apply/superglue_cpp/src/superglue.cpp:23:17: note: suggested alternative: ‘GraphExecutorState’ torch::jit::setGraphExecutorOptimize(false); ^~~~~~~~~~~~~~~~~~~~~~~~ GraphExecutorState `
> > > I assumed that I may cause by the version of libtorch. I am using version 1.0.1. I am wondering which version libtorch that you are using?
> > > Thanks,
> > 
> > 
> > the version is 1.6.0
> 
> ```c++
>     torch::jit::getProfilingMode() = false;
>     torch::jit::getExecutorMode() = false;
>     torch::jit::setGraphExecutorOptimize(false);
> ```
> 
> 是用来取消初次使用的一些优化来缩短初次的运行的时间，你也可以将他们注释掉

Great thank you, I will try it.
