### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Yeah2333** [mingjitianming/superglue_apply#5]
Thanks for your c++ superglue code . But when i compile this code , there are some error :
/home/wangzhiyong/superglue_apply/superglue_cpp/src/superpoint.cpp: In member function ‘auto SuperPoint::removeBorders(at::Tensor&, at::Tensor&, int, int, int)’:
/home/wangzhiyong/superglue_apply/superglue_cpp/src/superpoint.cpp:41:57: error: no matching function for call to ‘at::Tensor::index(at::Tensor)’
     return std::make_pair(keypoints.index(mask.squeeze()), scores.index(mask.squeeze()));

/home/wangzhiyong/libtorch-cxx11-abi-shared-with-deps-1.8.1+cu102/libtorch/include/ATen/core/TensorBody.h:822:10: note:   no known conversion for argument 1 from ‘at::Tensor’ to ‘const c10::List<c10::optional<at::Tensor> >&’
/home/wangzhiyong/superglue_apply/superglue_cpp/src/superpoint.cpp:41:87: error: no matching function for call to ‘at::Tensor::index(at::Tensor)’
     return std::make_pair(keypoints.index(mask.squeeze()), scores.index(mask.squeeze()));

/home/wangzhiyong/libtorch-cxx11-abi-shared-with-deps-1.8.1+cu102/libtorch/include/ATen/core/TensorBody.h:822:10: note:   no known conversion for argument 1 from ‘at::Tensor’ to ‘const c10::List<c10::optional<at::Tensor> >&’
/home/wangzhiyong/superglue_apply/superglue_cpp/src/superpoint.cpp: In member function ‘auto SuperPoint::calcKeyPoints(at::Tensor&&)’:
/home/wangzhiyong/superglue_apply/superglue_cpp/src/superpoint.cpp:58:10: error: ‘void <anonymous>’ has incomplete type
     auto [keypoints, scores] = removeBorders(keypts, keypts_score, remove_borders_, score[0].size(0), score[0].size(1))

/home/wangzhiyong/superglue_apply/superglue_cpp/src/superpoint.cpp: In member function ‘std::pair<std::vector<cv::KeyPoint>, cv::Mat> SuperPoint::detect(const cv::Mat&)’:
/home/wangzhiyong/superglue_apply/superglue_cpp/src/superpoint.cpp:104:10: error: ‘void <anonymous>’ has incomplete type
     auto [keypoints, scores] = calcKeyPoints(std::move(out->elements()[0].toTensor()));

/home/wangzhiyong/superglue_apply/superglue_cpp/src/superpoint.cpp:115:105: error: expected primary-expression before ‘float’
     cv::Mat desc_mat(cv::Size(descriptors.size(0), descriptors.size(1)), CV_32FC1, descriptors.data_ptr<float>());
                                                                                                         ^~~~~
/home/wangzhiyong/superglue_apply/superglue_cpp/src/superglue.cpp: In member function ‘std::tuple<std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> > > SuperGlue::match(std::vector<cv::KeyPoint>&, std::vector<cv::KeyPoint>&, cv::Mat&, cv::Mat&)’:
/home/wangzhiyong/superglue_apply/superglue_cpp/src/superglue.cpp:149:66: error: cannot bind rvalue reference of type ‘const at::Tensor&&’ to lvalue of type ‘at::Tensor’
     auto scores = logOptimalTransport(out->elements()[0].toTensor(), out->elements()[1].toTensor(), sinkhorn_iterations_);

my libtorch version is 1.8, and cuda version is 10.2

**Comment by Yeah2333** [comment]
@mingjitianming  I have use both pre-cx11 ABI and cx11 ABI, still have this error

**Comment by mingjitianming** [comment]
> @mingjitianming I have use both pre-cx11 ABI and cx11 ABI, still have this error

Hello, the version I use is pytorch 1.6 and the corresponding cxx11 ABI，and using some feature of c++17.
This error may be caused by the api change from 1.6 to 1.8，I don't have version 1.8 environment now, please refer to [index](https://pytorch.org/cppdocs/notes/tensor_indexing.html?highlight=index) and [index](https://pytorch.org/cppdocs/api/function_namespaceat_1af1152a41061673382ce204faa02f4755.html?highlight=index) to solve it.
thank you!

**Comment by Yeah2333** [comment]
> > @mingjitianming I have use both pre-cx11 ABI and cx11 ABI, still have this error
> 
> Hello, the version I use is pytorch 1.6 and the corresponding cxx11 ABI，and using some feature of c++17.
> This error may be caused by the api change from 1.6 to 1.8，I don't have version 1.8 environment now, please refer to [index](https://pytorch.org/cppdocs/notes/tensor_indexing.html?highlight=index) and [index](https://pytorch.org/cppdocs/api/function_namespaceat_1af1152a41061673382ce204faa02f4755.html?highlight=index) to solve it.
> thank you!

Hello, I have change keypoints.index(mask.squeeze()) to keypoints.index({mask.squeeze()}) . And then ,superpoint compile complete. But i still have some error with superglue's function  auto logOptimalTransport(const torch::Tensor&& scores, torch::Tensor &&alpha, const int iters);

/home/wangzhiyong/superglue_apply/superglue_cpp/src/superglue.cpp: In member function ‘std::tuple<std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> > > SuperGlue::match(std::vector<cv::KeyPoint>&, std::vector<cv::KeyPoint>&, cv::Mat&, cv::Mat&)’:
/home/wangzhiyong/superglue_apply/superglue_cpp/src/superglue.cpp:149:66: error: cannot bind rvalue reference of type ‘at::Tensor&&’ to lvalue of type ‘at::Tensor’
     auto scores = logOptimalTransport(out->elements()[0].toTensor(), out->elements()[1].toTensor(), sinkhorn_iterations_);

I don't konw how to change it.

**Comment by Yeah2333** [comment]
I have change auto SuperGlue::logOptimalTransport(const torch::Tensor &&scores, torch::Tensor &&alpha, const int iters) to auto SuperGlue::logOptimalTransport(const torch::Tensor &scores, torch::Tensor &alpha, const int iters) . And the compile complete. 
Is there any other way to solve this problem

**Comment by mingjitianming** [comment]
> I have change auto SuperGlue::logOptimalTransport(const torch::Tensor &&scores, torch::Tensor &&alpha, const int iters) to auto SuperGlue::logOptimalTransport(const torch::Tensor &scores, torch::Tensor &alpha, const int iters) . And the compile complete.
> Is there any other way to solve this problem

This is a question about the left value and the right value in c++11. and you can also use std::move to handle it
