### ISSUE TITLE
你好，非常感谢您的代码，我在使用您的代码进行相关测试的过程中，出现了一些问题，困扰了我很久，还望您能提供相关的指导和建议。

### ISSUE THREAD

**Issue by kevinJinm** [mingjitianming/superglue_apply#8]
我将代码中的kpts0和kpts1换成了相机的左右目图像进行匹配，代码如下：
auto [indice_left, scores_left, indice_right, scores_right] = sg.match(kpts_left, kpts_right, desc_left, desc_right);
    vector<KeyPoint> mkpts_base_left, mkpts_base_right;
    vector<KeyPoint> mkpts_base_left_db, mkpts_base_right_db;
    vector<Point3d> mkpts_base_3d, mkpts_base_3d_db;
    Mat mdesc_base_left_db, mdesc_base_left;
    // // 保留kpts0中的匹配点
    cout << "原始特征点数量: " << kpts_left.size() <<endl;
    int nMatchedNum=0;
    for(int j = 0; j < kpts_left.size(); ++j)
    {
        if(indice_left[j] != -1)
        {
            mkpts_base_left.push_back(kpts_left[j]);
            mdesc_base_left.push_back(desc_left.row(j));
            mkpts_base_right.push_back(kpts_right[indice_left[j]]);//获得kpts1中匹配点所在的行数
            nMatchedNum++;    //统计匹配点数
        }
    }
    // 测试
    auto [indice_left_base, scores_left_base, indice_right_query, scores_right_query] = sg.match(mkpts_base_left, kpts_right, mdesc_base_left, desc_right);
在这一段代码中，滤除了kpts_left中未匹配的特征点，同时滤除了对应的描述子，（使用的是push_back,同时在计算匹配点数量后，使用过desc_left.row(j).copyTo(mdesc_base_left.row(i))语句进行过拷贝）但是当我将滤除过后的特征点mkpts_base_left和描述子mdesc_base_left再次与右目特征点kpts_right和描述子desc_right匹配时，结果是不能匹配，indice_left_base中的值都为-1。实际上我的只是滤除了未匹配点，剩下的应该都是能匹配上的，但是一直没有找到错误的原因，还望您能够提供一点相关的解决思路，谢谢您，期待您的回复

**Comment by szgy66** [comment]
您好，请问你编译过了？我这边好多接口用法直接报错啊，尤其是&操作，这个libtorch是不支持的啊

**Comment by kevinJinm** [comment]
> 您好，请问你编译过了？我这边好多接口用法直接报错啊，尤其是&操作，这个libtorch是不支持的啊
我用的是1.6的libtorch，目前没有问题，然后权重文件再python下使用torch1.6进行转换

**Comment by szgy66** [comment]
> > 您好，请问你编译过了？我这边好多接口用法直接报错啊，尤其是&操作，这个libtorch是不支持的啊
> > 我用的是1.6的libtorch，目前没有问题，然后权重文件再python下使用torch1.6进行转换

请问他这三个文件夹，怎么编译啊

**Comment by kevinJinm** [comment]
> > > 您好，请问你编译过了？我这边好多接口用法直接报错啊，尤其是&操作，这个libtorch是不支持的啊
> > > 我用的是1.6的libtorch，目前没有问题，然后权重文件再python下使用torch1.6进行转换
> 
> 请问他这三个文件夹，怎么编译啊

编译第二个文件，第一个文件夹下的代码用于模型转换

**Comment by kevinJinm** [comment]
> > > > 您好，请问你编译过了？我这边好多接口用法直接报错啊，尤其是&操作，这个libtorch是不支持的啊
> > > > 我用的是1.6的libtorch，目前没有问题，然后权重文件再python下使用torch1.6进行转换
> > 
> > 
> > 请问他这三个文件夹，怎么编译啊
> 
> 编译第二个文件，第一个文件夹下的代码用于模型转换

还有就是，你将libtorch1.6放到主目录下，通过主目录下的cmakelists文件进行链接

**Comment by szgy66** [comment]
>主目录也没有cmakelists.txt啊，编译好久还是提示好多东西没有

**Comment by szgy66** [comment]
> > > > > 您好，请问你编译过了？我这边好多接口用法直接报错啊，尤其是&操作，这个libtorch是不支持的啊
> > > > > 我用的是1.6的libtorch，目前没有问题，然后权重文件再python下使用torch1.6进行转换
> > > 
> > > 
> > > 请问他这三个文件夹，怎么编译啊
> > 
> > 
> > 编译第二个文件，第一个文件夹下的代码用于模型转换
> 
> 还有就是，你将libtorch1.6放到主目录下，通过主目录下的cmakelists文件进行链接

主目录也没有cmakelists.txt啊，编译好久还是提示好多东西没有

**Comment by kevinJinm** [comment]
> > > > > > 您好，请问你编译过了？我这边好多接口用法直接报错啊，尤其是&操作，这个libtorch是不支持的啊
> > > > > > 我用的是1.6的libtorch，目前没有问题，然后权重文件再python下使用torch1.6进行转换
> > > > 
> > > > 
> > > > 请问他这三个文件夹，怎么编译啊
> > > 
> > > 
> > > 编译第二个文件，第一个文件夹下的代码用于模型转换
> > 
> > 
> > 还有就是，你将libtorch1.6放到主目录下，通过主目录下的cmakelists文件进行链接
> 
> 主目录也没有cmakelists.txt啊，编译好久还是提示好多东西没有

同学，认真看一下这三个文件夹下都是什么，搞清一下这个代码结构，你实际使用的代码在superglue_cpp这个文件夹中，编译也是对他编译，我所说的主目录也是说的这个文件夹，因为实际用的只有这个里面的内容，superglue/models只是用来进行模型转换的

**Comment by kevinJinm** [comment]
> > > > > > > 您好，请问你编译过了？我这边好多接口用法直接报错啊，尤其是&操作，这个libtorch是不支持的啊
> > > > > > > 我用的是1.6的libtorch，目前没有问题，然后权重文件再python下使用torch1.6进行转换
> > > > > 
> > > > > 
> > > > > 请问他这三个文件夹，怎么编译啊
> > > > 
> > > > 
> > > > 编译第二个文件，第一个文件夹下的代码用于模型转换
> > > 
> > > 
> > > 还有就是，你将libtorch1.6放到主目录下，通过主目录下的cmakelists文件进行链接
> > 
> > 
> > 主目录也没有cmakelists.txt啊，编译好久还是提示好多东西没有
> 
> 同学，认真看一下这三个文件夹下都是什么，搞清一下这个代码结构，你实际使用的代码在superglue_cpp这个文件夹中，编译也是对他编译，我所说的主目录也是说的这个文件夹，因为实际用的只有这个里面的内容，superglue/models只是用来进行模型转换的。
还有就是编译缺少一些东西，可能是你环境中一些库没有安装，你仔细看一下CmakeLists文件内容，看你对应的链接库有没有，主要搞懂CmakeLists的内容，代码是没有问题的，编译出错大概率是库这些没有链接到

**Comment by szgy66** [comment]
> > > > > > > > 您好，请问你编译过了？我这边好多接口用法直接报错啊，尤其是&操作，这个libtorch是不支持的啊
> > > > > > > > 我用的是1.6的libtorch，目前没有问题，然后权重文件再python下使用torch1.6进行转换
> > > > > > 
> > > > > > 
> > > > > > 请问他这三个文件夹，怎么编译啊
> > > > > 
> > > > > 
> > > > > 编译第二个文件，第一个文件夹下的代码用于模型转换
> > > > 
> > > > 
> > > > 还有就是，你将libtorch1.6放到主目录下，通过主目录下的cmakelists文件进行链接
> > > 
> > > 
> > > 主目录也没有cmakelists.txt啊，编译好久还是提示好多东西没有
> > 
> > 
> > 同学，认真看一下这三个文件夹下都是什么，搞清一下这个代码结构，你实际使用的代码在superglue_cpp这个文件夹中，编译也是对他编译，我所说的主目录也是说的这个文件夹，因为实际用的只有这个里面的内容，superglue/models只是用来进行模型转换的。
> > 还有就是编译缺少一些东西，可能是你环境中一些库没有安装，你仔细看一下CmakeLists文件内容，看你对应的链接库有没有，主要搞懂CmakeLists的内容，代码是没有问题的，编译出错大概率是库这些没有链

您好，我编译成功了，请问怎么测试呢，有相关的测试代码吗

**Comment by pazifik-cyber** [comment]
> 我将代码中的kpts0和kpts1换成了相机的左右目图像进行匹配，代码如下： auto [indice_left, scores_left, indice_right, scores_right] = sg.match(kpts_left, kpts_right, desc_left, desc_right); vector mkpts_base_left, mkpts_base_right; vector mkpts_base_left_db, mkpts_base_right_db; vector mkpts_base_3d, mkpts_base_3d_db; Mat mdesc_base_left_db, mdesc_base_left; // // 保留kpts0中的匹配点 cout << "原始特征点数量: " << kpts_left.size() <<endl; int nMatchedNum=0; for(int j = 0; j < kpts_left.size(); ++j) { if(indice_left[j] != -1) { mkpts_base_left.push_back(kpts_left[j]); mdesc_base_left.push_back(desc_left.row(j)); mkpts_base_right.push_back(kpts_right[indice_left[j]]);//获得kpts1中匹配点所在的行数 nMatchedNum++; //统计匹配点数 } } // 测试 auto [indice_left_base, scores_left_base, indice_right_query, scores_right_query] = sg.match(mkpts_base_left, kpts_right, mdesc_base_left, desc_right); 在这一段代码中，滤除了kpts_left中未匹配的特征点，同时滤除了对应的描述子，（使用的是push_back,同时在计算匹配点数量后，使用过desc_left.row(j).copyTo(mdesc_base_left.row(i))语句进行过拷贝）但是当我将滤除过后的特征点mkpts_base_left和描述子mdesc_base_left再次与右目特征点kpts_right和描述子desc_right匹配时，结果是不能匹配，indice_left_base中的值都为-1。实际上我的只是滤除了未匹配点，剩下的应该都是能匹配上的，但是一直没有找到错误的原因，还望您能够提供一点相关的解决思路，谢谢您，期待您的回复

您好，请问您编译过了？为什么我下载了libtorch并放在了主目录里，为什么cmake报错，提示没有caffee呢，cmakelists.txt里面需要添加啥么，期待你的帮助，谢谢

**Comment by kevinJinm** [comment]
> > 我将代码中的kpts0和kpts1换成了相机的左右目图像进行匹配，代码如下： auto [indice_left, scores_left, indice_right, scores_right] = sg.match(kpts_left, kpts_right, desc_left, desc_right); vector mkpts_base_left, mkpts_base_right; vector mkpts_base_left_db, mkpts_base_right_db; vector mkpts_base_3d, mkpts_base_3d_db; Mat mdesc_base_left_db, mdesc_base_left; // // 保留kpts0中的匹配点 cout << "原始特征点数量: " << kpts_left.size() <<endl; int nMatchedNum=0; for(int j = 0; j < kpts_left.size(); ++j) { if(indice_left[j] != -1) { mkpts_base_left.push_back(kpts_left[j]); mdesc_base_left.push_back(desc_left.row(j)); mkpts_base_right.push_back(kpts_right[indice_left[j]]);//获得kpts1中匹配点所在的行数 nMatchedNum++; //统计匹配点数 } } // 测试 auto [indice_left_base, scores_left_base, indice_right_query, scores_right_query] = sg.match(mkpts_base_left, kpts_right, mdesc_base_left, desc_right); 在这一段代码中，滤除了kpts_left中未匹配的特征点，同时滤除了对应的描述子，（使用的是push_back,同时在计算匹配点数量后，使用过desc_left.row(j).copyTo(mdesc_base_left.row(i))语句进行过拷贝）但是当我将滤除过后的特征点mkpts_base_left和描述子mdesc_base_left再次与右目特征点kpts_right和描述子desc_right匹配时，结果是不能匹配，indice_left_base中的值都为-1。实际上我的只是滤除了未匹配点，剩下的应该都是能匹配上的，但是一直没有找到错误的原因，还望您能够提供一点相关的解决思路，谢谢您，期待您的回复
> 
> 您好，请问您编译过了？为什么我下载了libtorch并放在了主目录里，为什么cmake报错，提示没有caffee呢，cmakelists.txt里面需要添加啥么，期待你的帮助，谢谢
抱歉，回复的太迟了，这段时间都没有登录github，cmakelists.txt里面不用修改，libtorch推荐使用1.6，其余的问题，大概是缺少相应的包或者库，尝试安装一下
